# Generated by Django 5.0.6 on 2024-07-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnyapp', '0002_alter_jobs_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jtitle',
            field=models.CharField(max_length=500),
        ),
    ]
